CALL SP_CLEAN_DB();

CALL SP_CREATE_PRIVILEGE('ADMINISTRADOR','TODOS LOS PRIVILEGIOS');
CALL SP_CREATE_PRIVILEGE('USUARIO DE SERVICIO','LECTURA / ESCRITURA , ALTAS Y BAJAS DE SERVICIOS, CONSULTAS');
CALL SP_CREATE_PRIVILEGE('CLIENTE','VISUALIZACION DE SERVICIOS / COMENTARIOS');

CALL SP_CREATE_JOB('RECEPCIONISTA',4000,6000);
CALL SP_CREATE_JOB('TECNICO',6000,8000);
CALL SP_CREATE_JOB('INTENDENTE',3600,4000);
CALL SP_CREATE_JOB('CONTADOR', 8000, 10000);
CALL SP_CREATE_JOB('INGENIERO',10000,12000);

CALL SP_CREATE_EVENT('EVENTO NO CONTROLADO','EVENTO GENERADO CUANDO LA LOGICA DEL PROGRAMA NO PUDO DETERMINAR EL TIPO DE EVENTO');
CALL SP_CREATE_EVENT('INICIO DE SESION','EVENTO GENERADO CUANDO UN USUARIO HA INGRESADO SESION EN EL SISTEMA');
CALL SP_CREATE_EVENT('CIERRE DE SESION','EVENTO GENERADO CUANDO UN USUARIO HA CERRADO SESION EN EL SISTEMA');
CALL SP_CREATE_EVENT('CIERRE DE INACTIVIDAD','EVENTO GENERADO CUANDO SE CIERRA SESION POR INACTIVIDAD');
CALL SP_CREATE_EVENT('ALTA USUARIO','EVENTO GENERADO CUANDO UN USUARIO HA DADO DE ALTA A UN USUARIO EN EL SISTEMA');

CALL SP_CREATE_PRODUCTCAT('SERVIDOR','UNIDAD DE PROCESOS CENTRALES CON GRANDES PRESTACIONES LLAMADO SERVIDOR');
CALL SP_CREATE_PRODUCTCAT('PC-CPU','COMPUTADORA PERSONAL CPU');
CALL SP_CREATE_PRODUCTCAT('LAPTOP','COMPUTADORA PERSONAL LAPTOP');
CALL SP_CREATE_PRODUCTCAT('SWITCH','SWITCH DE RED');
CALL SP_CREATE_PRODUCTCAT('ROUTER','ROUTER DE RED');
CALL SP_CREATE_PRODUCTCAT('FIREWALL','FIREWALL DE RED');

CALL SP_CREATE_FAILURE('GENERICA','FALLA GENERICA / SIN DIAGNOSTICO PREDECIBLE',2);
CALL SP_CREATE_FAILURE('FORMATEO','FORMATEO DE HDD CON INSTALACION DE SO',1);
CALL SP_CREATE_FAILURE('LIMPIEZA','LIMPIEZA DE COMPONENTES',1);
CALL SP_CREATE_FAILURE('REEMPLAZO DE PIEZAS, EXISTENCIA','REEMPLAZO DE PIEZAS DANADAS',2);
CALL SP_CREATE_FAILURE('REEMPLAZO DE PIEZAS, SIN EXISTENCIA','REEMPLAZO DE PIEZAS DANADAS',5);

CALL SP_CREATE_USER('JESUS JOSE','NAVARRETE BACA','NABJ970430','NABJ970430HCHVCS07','CUMBRES DEL MOHINORA','FRACCIONAMIENTO CUMBRES I','4201','31124','1997-04-30','CHIHUAHUA','CHIHUAHUA','a301422@uach.mx','6144458879','6271236698');
CALL SP_CREATE_USER('RAUL JOSE','NAVARRETE HIPSON','NABJ970420','NABJ970420HCHVCS08','CUMBRES DEL MOHINORA','FRACCIONAMIENTO CUMBRES I','4201','31124','1997-04-30','CHIHUAHUA','CHIHUAHUA','a301429@uach.mx','6144458879','6271236698');
CALL SP_CREATE_USER('ROMULO JOSE','NAVARRETE CURVAL','NABJ970450','NABJ970450HCHVCS09','CUMBRES DEL MOHINORA','FRACCIONAMIENTO CUMBRES I','4201','31124','1997-04-30','CHIHUAHUA','CHIHUAHUA','a305429@uach.mx','6144458879','6271236698');


CALL SP_CREATE_EMPLOYEE('NABJ970430HCHVCS07','INGENIERO',NULL,NULL);
CALL SP_CREATE_EMPLOYEE('NABJ970420HCHVCS08','RECEPCIONISTA',NULL,NULL);

CALL SP_CREATE_CREDENTIALS('ADMIN','ADMIN','ADMINISTRADOR','NABJ970430HCHVCS07');
CALL SP_CREATE_CREDENTIALS('usr','usr', 'USUARIODESERVICIO','NABJ970420HCHVCS08');







