/*TRIGGER QUE SE EJECUTA EN PRODUCTS ANTES DE INSERT*/
DROP TRIGGER IF EXISTS TRIG_PRODUCTS_BI;
DELIMITER $$
CREATE TRIGGER TRIG_PRODUCTS_BI BEFORE INSERT ON PRODUCTS FOR EACH ROW
BEGIN
	DECLARE XIDENTIFICADOR VARCHAR(100) DEFAULT NULL;
    
    DECLARE IDPROD INT DEFAULT 1;
    
    BEGIN
		SELECT MAX(ID) + 1 INTO IDPROD FROM PRODUCTS;
        
        IF(IDPROD IS NULL) THEN
			SET IDPROD = 1;
        END IF;
    END;
            
    SELECT CONCAT(IDPROD,NEW.NUMERO_SERIE,NEW.ORDERS_ID,NEW.CATEGORIA_ID) INTO XIDENTIFICADOR FROM DUAL;
    
    SET NEW.IDENTIFICADOR = XIDENTIFICADOR;
END;

$$
/*TRIGGER QUE SE EJECUTA EN SERVICE_ORDERS ANTES DE INSERT*/
DROP TRIGGER IF EXISTS TRIG_SERVICE_ORDERS_BI;
DELIMITER $$
CREATE TRIGGER TRIG_SERVICE_ORDERS_BI  BEFORE INSERT ON SERVICE_ORDERS FOR EACH ROW
BEGIN
	DECLARE CID INT;
    SELECT ID INTO CID FROM CUSTOMERS WHERE USER_ID = NEW.USER_ID;	
    SET NEW.CUSTOMER_ID = CID;
END;

$$

/*TRIGGER QUE SE EJECUTA EN CUSTOMERS DESPUES DE INSERT*/
DROP TRIGGER IF EXISTS TRIG_USER_AI_CUST;
DELIMITER $$
CREATE TRIGGER TRIG_USER_AI_CUST AFTER INSERT ON USERS FOR EACH ROW
BEGIN	
	INSERT INTO CUSTOMERS(USER_ID) VALUES(NEW.ID);

END ;

$$

/*TRIGGER QUE SE EJECUTA EN EVENTS ANTES DE INSERT*/
DROP TRIGGER IF EXISTS TRIG_EVENTS_BI;
DELIMITER $$
CREATE TRIGGER TRIG_EVENTS_BI BEFORE INSERT ON EVENTS FOR EACH ROW
BEGIN
	
    DECLARE GENCODE VARCHAR(40);
    DECLARE DEF VARCHAR(20);
    DECLARE AIP INT;
    
    SET DEF = 'SETWEBID_';
    
	SET AIP = GET_NEXTID_EVENTS();
    
    IF(CHAR_LENGTH(NEW.NAME) > 5) THEN
		
		SET GENCODE = CONCAT(REPLACE(NEW.NAME,' ',''),"_",AIP);
    
    ELSE
    
		SET GENCODE = CONCAT(DEF,AIP);
    
    END IF;
    
    SET NEW.CODE = GENCODE;
    
END ;
$$

/*TRIGGER QUE SE EJECUTA EN REGISTERS ANTES DE INSERT*/
DROP TRIGGER IF EXISTS TRIG_REGISTERS_BI;
DELIMITER $$
CREATE TRIGGER TRIG_REGISTERS_BI BEFORE INSERT ON REGISTERS FOR EACH ROW
BEGIN
	SET NEW.FECHA = CURRENT_DATE();
    SET NEW.HORA = CURRENT_TIME();
END ;
$$

