<?php
  $SP_INSERT_USR = "CALL SP_CREATE_USER(?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?, ?, ?, ?)";
  $SP_INSERT_CUST = "CALL SP_CREATE_CUSTOMER(?,?,?)";
  $SP_LOGIN = "CALL SP_LOGIN(?, ?)";
  $SP_USRNAME = "CALL SP_EXIST_USRNAME(?)";
  $SP_DELETEUSR = "CALL SP_DELETE_USER(?)";
  $SP_INSERT_EVENT = "CALL SP_CREATE_REGISTER(?,?)";
  $SP_INSERT_EVENT2 = "CALL SP_CREATE_REGISTER_COMM(?,?,?)";
  $SP_GETUSRTYPE = "CALL SP_GET_USR_TYPE(?)";
  $SP_GET_REGISTERS_USRDATE = "CALL SP_REGISTERS_COMPLEX1(?,?,?,?)";
  $SP_GET_CATEGORIES_PRODUCTS = "CALL SP_GET_PRODUCTS_CATEGORIES";
  $SP_GET_ORDEN_ID = "CALL SP_GET_ORDEN_NUMBER";
  $SP_CREATE_ORDER = "CALL SP_CREATE_SERVICE_ORDER(?,?,?,?)";
  $SP_EXIST_CURP = "CALL SP_EXIST_CURP(?)";
  $SP_INSERT_PRODUCT = "CALL SP_INSERT_PRODUCT(?,?,?,?,?,?)";
  $SP_CANCEL_SERVICE_ORDER = "CALL SP_CANCEL_ORDER(?)";
?>
