<?php
//$_SERVER['DOCUMENT_ROOT'].'/websys/LOGIC/pagination/XVARS_php.php'

  $SESVAR = 'login_user'; //CURRENT USER ALIAS NAME

  $FLAG_LOGIN_MODAL = 'flag_login_modal'; //FLAG TO MODAL IN LOGIN MECHANISM

  $TABLE_EVENTS_REGISTERS = 'event_registers_php'; //TABLE DATA OF EVENTS_REGISTERS AS ASSOCIATIVE ARRAY

  $TIME_RECORD = 'last_time_record'; //USED TO CHECK THE LAST USER ACTIVITY

  $INACTIVE_LAPSE = 1500; // LAPSE IN SECONDS OF INACTIVITY
?>
